kind: Secret
apiVersion: v1
metadata:
  name: telegram-bot-secret
type: Opaque
stringData:
  TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
  LLM_URL: "${LLM_URL}"
  LLM_TOKEN: "${LLM_TOKEN}"
  MODEL_NAME: "${MODEL_NAME}"
  