load('ext://dotenv', 'dotenv')
dotenv(fn='.env')
watch_file('.env')


################################################################################
# ------------------------ Apps ------------------------------------------------
################################################################################

# ------------------------ Bot APP ---------------------------------------------
docker_build(
    "rawthil_stdout_bot:dev",
    context="../app",
    dockerfile="../app/Dockerfile",
    live_update=[]  # dummy live_update to trigger builds
)


# ------------------------------------------------------------------------------
# ------------------------ Env Vars Substitution -------------------------------
# ------------------------------------------------------------------------------
def replce_file(input, output):
    watch_file(input)
    local("envsubst < " + input + " > " + output, dir = '.')
    watch_settings(ignore=output)

# ------------------------ Bot APP ---------------------------------------------

replce_file(
    "./apps/telegram-bot/local/resources/secret.template.yaml",
    "./apps/telegram-bot/local/resources/secret.yaml",
    )

# ------------------------------------------------------------------------------
# ------------------------ Deploy ----------------------------------------------
# ------------------------------------------------------------------------------

# ------------------------ Bot APP ---------------------------------------------
k8s_yaml([
    kustomize('./apps/telegram-bot/local'),
    ])

# Telegram Bot
k8s_resource("telegram-bot", labels=["telegram-bot"])
